/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Hand History
         * @description Accept a raw hand-history (or summary) file, stage it in MinIO, enqueue async parsing.
         *
         *     The heavy parsing happens out-of-band in the worker (Rust ``hh_parser``); the request
         *     returns as soon as the file is staged so uploads stay fast under bulk imports.
         */
        post: operations["upload_hand_history_ingest_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Bulk
         * @description Accept a large bundle of concatenated hand-history (or summary) files in one request.
         *
         *     The browser concatenates many small files into ~16 MB chunks and gzips them, turning a
         *     base of hundreds of thousands of files into a few dozen requests. The body is the raw
         *     bundle; ``X-Bundle-Gzip: 1`` marks gzip-compressed payloads. We store the gzip **as-is**
         *     (5-10x smaller) and let the worker decompress on read — the staged object is transient and
         *     deleted once parsed. The worker's parsers are multi-record, so one object yields all its
         *     hands/tournaments in a single pass.
         */
        post: operations["upload_bulk_ingest_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Archive
         * @description Accept a single archive (zip/rar/7z/tar/gz/…) and extract its .txt members server-side.
         *
         *     The raw archive is staged as-is (already compressed); the worker uses libarchive to pull out
         *     the hand-history/summary files and feeds them through the normal parse + dedup pipeline.
         */
        post: operations["upload_archive_ingest_archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_stats_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hands/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent */
        get: operations["recent_hands_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Import Summary */
        get: operations["import_summary_imports__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_hand_history_ingest_upload_post */
        Body_upload_hand_history_ingest_upload_post: {
            /** File */
            file: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** ImportSummary */
        ImportSummary: {
            /** Chunks */
            chunks: number;
            /** Done */
            done: number;
            /** Failed */
            failed: number;
            /** Pending */
            pending: number;
            /** Complete */
            complete: boolean;
            /** Hands Added */
            hands_added: number;
            /** Hands Skipped */
            hands_skipped: number;
            /** Tournaments Added */
            tournaments_added: number;
            /** Tournaments Skipped */
            tournaments_skipped: number;
        };
        /** Overview */
        Overview: {
            /** Total Hands */
            total_hands: number;
            /** Total Tournaments */
            total_tournaments: number;
            /** Avg Multiplier */
            avg_multiplier: number;
            /** By Stack */
            by_stack: components["schemas"]["StackBucket"][];
        };
        /** RecentHand */
        RecentHand: {
            /** Source Hand Id */
            source_hand_id: string;
            /** Played At */
            played_at: string;
            /** Tournament Format */
            tournament_format: string;
            /** Effective Stack Bb */
            effective_stack_bb: number;
            /** Position */
            position: string;
            /** Result */
            result: number;
            /** Board */
            board: string;
        };
        /** StackBucket */
        StackBucket: {
            /** Effective Stack Bb */
            effective_stack_bb: number;
            /** Hands */
            hands: number;
            /** Result */
            result: number;
            /** Winrate */
            winrate: number;
        };
        /** UploadResult */
        UploadResult: {
            /** Object Key */
            object_key: string;
            /** Bytes */
            bytes: number;
            /** Queued */
            queued: boolean;
            /** Import Id */
            import_id: string;
            /** Session Id */
            session_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    upload_hand_history_ingest_upload_post: {
        parameters: {
            query?: never;
            header?: {
                "x-upload-session"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_hand_history_ingest_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_bulk_ingest_bulk_post: {
        parameters: {
            query?: never;
            header?: {
                "x-upload-session"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_archive_ingest_archive_post: {
        parameters: {
            query?: never;
            header?: {
                "x-upload-session"?: string | null;
                "x-filename"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_stats_overview_get: {
        parameters: {
            query?: {
                format?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recent_hands_recent_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecentHand"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_summary_imports__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
